# Fix java for DWM 
#wmname LG3D &

# Background 
#xsetroot -solid "#1c1c1c" &

# Brightness 
#xbacklight -set 0 &

# Fonts 
#xset fp+ /usr/share/fonts/local &

# Keyboard
setxkbmap -layout es &

# Kill X
##setxkbmap -option terminate:ctrl_alt_bksp

# Load .Xresources
if [ -f ~/.Xresources.local ]; then
	xrdb -merge ~/.Xresources.local
elif [ -f ~/.Xresources.${HOSTNAME} ]; then
	xrdb -merge ~/.Xresources.${HOSTNAME}
elif [ -f ~/.Xresources ]; then
	xrdb -merge ~/.Xresources
fi

# Init scripts
[[ -f ~/bin/scripts/init.sh ]] && ~/bin/scripts/init.sh 
[[ -f ~/bin/scripts/init.${HOSTNAME}.sh ]] && ~/bin/scripts/init.${HOSTNAME}.sh 
